### ISSUE TITLE
1. MOBILE WEB

### ISSUE THREAD

**Issue by AlejandraMejiaP** [Adalab/project-promo-o-modulo-1-team-9#6]
_mobile web version_ 

**RESOURCES** 

- A group name
- A group claim
- A group photo
- A group description
- Group strengths and weaknesses
- Group members info: name, photo, social links
- Mobile design

**Tasks**

- [ ] Define content for the web
- [ ] Header of the home page
- [ ] Hero of the home page
- [ ] About us of the home page
- [ ] Strengths & weaknesses of the home page
- [ ] Footer of the home page
